version: 2.1

executors:
  mac-executor:
    macos:
      xcode: 14.2.0 # adjust based on your local Xcode version
    working_directory: ~/project

jobs:
  build:
    executor: mac-executor
    steps:
      - checkout
      - run:
          name: Build iOS Project
          command: |
            xcodebuild clean build \
              -project CICDDemo.xcodeproj \
              -scheme CICDDemo \
              -sdk iphonesimulator \
              -destination 'platform=iOS Simulator,name=iPhone 14'

workflows:
  version: 2
  build-and-test:
    jobs:
      - build
