version: 2.1

executors:
  mac-executor:
    macos:
      xcode: 14.2.0
    working_directory: ~/project

jobs:
  build:
    executor: mac-executor
    steps:
      - checkout
      - run:
          name: Install CocoaPods (via Homebrew)
          command: |
            brew install cocoapods
            pod install
      - run:
          name: Build the App
          command: |
            xcodebuild clean build \
              -workspace CICDDemo.xcworkspace \
              -scheme CICDDemo \
              -sdk iphonesimulator \
              -destination 'platform=iOS Simulator,name=iPhone 14'

workflows:
  version: 2
  build-and-test:
    jobs:
      - build
