version: 2.1

executors:
  macos-executor:
    macos:
      xcode: "16.0.0"
    working_directory: ~/project

jobs:
  build-and-test:
    executor: macos-executor
    steps:
      - checkout

      - run:
          name: Build iOS App (iPhone 16)
          command: |
            xcodebuild clean build \
              -project CircleCIDemo.xcodeproj \
              -scheme CircleCIDemo \
              -sdk iphonesimulator \
              -destination "platform=iOS Simulator,name=iPhone 16" \
              CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
      - run:
          name: Run Unit Tests
          command: |
            xcodebuild test \
              -project CircleCIDemo.xcodeproj \
              -scheme CircleCIDemo \
              -sdk iphonesimulator \
              -destination "platform=iOS Simulator,name=iPhone 16" \
              CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO

workflows:
  version: 2
  build:
    jobs:
      - build-and-test
